# Script to process 0.25° GPM IMERG Late Precipitation data
# Integrated Multi-satEllite Retrieval for Global Precipitation Measurement (GPM)
# Generated by the Precipitation Processing System (PPS)
# Algorithm Version: 3IMERGH 7.0
# Optimized R script version: v2.0

#///////////////////////////////////////////////////////////////////////////////

# SECTION 1: PACKAGE LOADING ----
#///////////////////////////////////////////////////////////////////////////////

# Load required packages
required_packages <- c("terra", "sf", "dplyr", "stringr")
invisible(lapply(required_packages, library, character.only = TRUE))

# SECTION 2: CONFIGURATION ----
#///////////////////////////////////////////////////////////////////////////////

# Define main directories
dir_config <- list(
  main = normalizePath("C:/ONCC_IMERG"),
  aoi = file.path("C:/ONCC_IMERG", "AOI"),
  input = file.path("C:/ONCC_IMERG", "Input"),
  raw_input = file.path("C:/ONCC_IMERG", "RawInput"),
  output = file.path("C:/ONCC_IMERG", "Outcome"),
  pattern = file.path("C:/ONCC_IMERG", "Pattern", "pattern_1km.tif")
)

# Precipitation scaling factor for IMERG data at 30-minute intervals
scaling_factor <- 0.1

# Missing data for IMERG data at 30-minute intervals
missing_data <- 29999

# SECTION 3: PROCESSING FUNCTIONS ----
#///////////////////////////////////////////////////////////////////////////////

# Function to clean up temporary files
clean_directory <- function(path, patterns) {
  list.files(path, pattern = paste(patterns, collapse = "|"), full.names = TRUE) |>
    file.remove()
}

# Function to load AOI shapefiles
load_aoi <- function(pattern, dir_path = dir_config$aoi) {
  list.files(dir_path, pattern, full.names = TRUE) |>
    st_read(quiet = TRUE) |>
    vect()
}

# Function to process raster files
process_raster <- function(file_path, template, aoi) {
  rast(file_path) |>
    resample(template, method = "bilinear") |>
    mask(aoi)
}

# Function to delete files and folders
deleteFilesAndFolders <- function(folder) {
  # Check if the folder exists
  if (!dir.exists(folder)) {
    stop("Folder does not exist")
  }
  # Get all items in the folder (both files and directories)
  all_items <- list.files(folder, full.names = TRUE)
  # Identify which items are directories
  is_directory <- dir.exists(all_items)
  # Separate files and directories
  files <- all_items[!is_directory]
  directories <- all_items[is_directory]
  # Delete files first
  if (length(files) > 0) {
    file.remove(files)
  }
  # Delete directories (including their contents)
  if (length(directories) > 0) {
    unlink(directories, recursive = TRUE)
  }
  # Return confirmation message
  paste("All files and folders in", folder, "have been deleted")
}

# SECTION 4: DATA PREPARATION ----
#///////////////////////////////////////////////////////////////////////////////

# Load spatial data
template_raster <- rast(dir_config$pattern)
venezuela_aoi <- load_aoi("Venezuela")

# Define regions for processing
regions <- list(
  Cojedes = load_aoi("Cojedes"),
  Guarico = load_aoi("Guarico"),
  Venezuela = load_aoi("Venezuela")
)

# SECTION 5: DATA PROCESSING PIPELINE FOR 30-MINUTES RAINFALL ----
#///////////////////////////////////////////////////////////////////////////////

# Move the tif files from raw data folder to the input folder
repository <- list.files(path = dir_config$raw_input,
                         pattern = "3B-HHR.*\\.30min.tif$",
                         full.names = TRUE)

base::file.copy(from = repository,
                to = dir_config$input,
                overwrite = TRUE,
                copy.mode = TRUE,
                copy.date = FALSE)

# Setting the time and date
imerg_files <- list.files(dir_config$input, full.names = TRUE)
F1 <- unlist(strsplit(basename(imerg_files[1]), ".", fixed = TRUE))
F2 <- unlist(strsplit(F1[5], "-", fixed = TRUE))

# Customizable Parameters
date_str <- F2[1]        # Original date in YYYYMMDD format
utc_offset <- -4         # UTC offset for conversion (e.g., -4 for UTC-4)
time_step <- 0.5         # Time step in hours (0.5 = 30 minutes)

# Core Processing
# Convert date to POSIXct for precise datetime calculations
base_date <- as.POSIXct(date_str, format = "%Y%m%d", tz = "UTC")

# Generate sequence of time points (in hours from 0 to 23.5)
time_points <- seq(0, 23.5, by = time_step)

# Create UTC datetimes using vectorized operations
utc_datetimes <- base_date + time_points * 3600

# Calculate local datetimes with date rollover
local_datetimes <- utc_datetimes + utc_offset * 3600

# Formatting Results
# Create formatted time-date strings
tag <- paste0(
  format(local_datetimes, "S%H%M00."),
  format(local_datetimes, "%Y%m%d")
)

# Process 30-minutes precipitation data [native units = "mm/hr"]
a <- length(imerg_files)
for (i in 1:a) {
  r <- process_raster(file_path = imerg_files[i],
                       template = template_raster,
                       aoi = regions$Venezuela)

  r[r == missing_data] <- NA  # Set missing data to NA
  rc <- r * scaling_factor * time_step # Convert from mm/hr to mm

  fname_base <- unlist(strsplit(names(r), ".", fixed = TRUE))

  fname <- paste(c(fname_base[4], tag[i], "tif"), collapse = ".")

  writeRaster(rc, file.path(dir_config$output, fname), overwrite = TRUE)
}

# SECTION 6: CLEAN THE INPUT FOLDER ----
deleteFilesAndFolders(dir_config$raw_input)
deleteFilesAndFolders(dir_config$input)
# deleteFilesAndFolders(dir_config$output) BE CAREFUL. NOT RUN

#///////////////////////////////////////////////////////////////////////////////

# End of script
rm(list = ls(all.names = TRUE, envir = .GlobalEnv))  # Clear all objects including hidden
invisible(gc())  # Force garbage collection
cat("\f")  # More universal form feed character
# Close all open connections
quit(save = "no", status = 0)
